// <auto-generated />
namespace QuanLyNhaSach.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Add_StoreProc3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_StoreProc3));
        
        string IMigrationMetadata.Id
        {
            get { return "201504220228118_Add_StoreProc3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
