// <auto-generated />
namespace QuanLyNhaSach.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class change_password_length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_password_length));
        
        string IMigrationMetadata.Id
        {
            get { return "201506240316503_change_password_length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
