// <auto-generated />
namespace QuanLyNhaSach.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Drop_ManytoMany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Drop_ManytoMany));
        
        string IMigrationMetadata.Id
        {
            get { return "201504240308139_Drop_ManytoMany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
