// <auto-generated />
namespace QuanLyNhaSach.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ManytoMany_Relationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ManytoMany_Relationship));
        
        string IMigrationMetadata.Id
        {
            get { return "201504240259364_ManytoMany_Relationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
