// <auto-generated />
namespace QuanLyNhaSach.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class delete_attribute_cthoadonbanhang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_attribute_cthoadonbanhang));
        
        string IMigrationMetadata.Id
        {
            get { return "201505261852193_delete_attribute_cthoadonbanhang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
